# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/array.proto

require 'google/protobuf'


descriptor_data = "\n\x1bprotip/messages/array.proto\x12\x0fprotip.messages\"\x19\n\x05\x41rray\x12\x10\n\x08messages\x18\x01 \x03(\x0c\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    Array = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.Array").msgclass
  end
end
