# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/big_decimal_value.proto

require 'google/protobuf'


descriptor_data = "\n\'protip/messages/big_decimal_value.proto\x12\x0fprotip.messages\"L\n\x0f\x42igDecimalValue\x12\x11\n\tnumerator\x18\x01 \x01(\x03\x12\x13\n\x0b\x64\x65nominator\x18\x02 \x01(\x04\x12\x11\n\tprecision\x18\x03 \x01(\rb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    BigDecimalValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.BigDecimalValue").msgclass
  end
end
