# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/errors.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protip/messages/errors.proto", :syntax => :proto3) do
    add_message "protip.messages.Errors" do
      repeated :messages, :string, 1
      repeated :field_errors, :message, 2, "protip.messages.FieldError"
    end
    add_message "protip.messages.FieldError" do
      optional :field, :string, 1
      optional :message, :string, 2
    end
  end
end

module Protip
  module Messages
    Errors = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.Errors").msgclass
    FieldError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.FieldError").msgclass
  end
end
