# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/errors.proto

require 'google/protobuf'


descriptor_data = "\n\x1cprotip/messages/errors.proto\x12\x0fprotip.messages\"M\n\x06\x45rrors\x12\x10\n\x08messages\x18\x01 \x03(\t\x12\x31\n\x0c\x66ield_errors\x18\x02 \x03(\x0b\x32\x1b.protip.messages.FieldError\",\n\nFieldError\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    Errors = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.Errors").msgclass
    FieldError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.FieldError").msgclass
  end
end
