# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/money.proto

require 'google/protobuf'

require 'protip/messages/currency_pb'


descriptor_data = "\n\x1bprotip/messages/money.proto\x12\x0fprotip.messages\x1a\x1eprotip/messages/currency.proto\"J\n\x05Money\x12\x14\n\x0c\x61mount_cents\x18\x01 \x01(\x03\x12+\n\x08\x63urrency\x18\x02 \x01(\x0b\x32\x19.protip.messages.Currencyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    Money = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.Money").msgclass
  end
end
