# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/range.proto

require 'google/protobuf'


descriptor_data = "\n\x1bprotip/messages/range.proto\x12\x0fprotip.messages\"#\n\x05Range\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    Range = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.Range").msgclass
  end
end
