# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/repeated_wrappers.proto

require 'google/protobuf'

require 'protip/extensions_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protip/messages/repeated_wrappers.proto", :syntax => :proto3) do
    add_message "protip.messages.RepeatedDouble" do
      repeated :values, :double, 1
    end
    add_message "protip.messages.RepeatedFloat" do
      repeated :values, :float, 1
    end
    add_message "protip.messages.RepeatedInt64" do
      repeated :values, :int64, 1
    end
    add_message "protip.messages.RepeatedUInt64" do
      repeated :values, :uint64, 1
    end
    add_message "protip.messages.RepeatedInt32" do
      repeated :values, :int32, 1
    end
    add_message "protip.messages.RepeatedUInt32" do
      repeated :values, :uint32, 1
    end
    add_message "protip.messages.RepeatedBool" do
      repeated :values, :bool, 1
    end
    add_message "protip.messages.RepeatedString" do
      repeated :values, :string, 1
    end
    add_message "protip.messages.RepeatedBytes" do
      repeated :values, :bytes, 1
    end
    add_message "protip.messages.RepeatedEnum" do
      repeated :values, :int32, 1
    end
  end
end

module Protip
  module Messages
    RepeatedDouble = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedDouble").msgclass
    RepeatedFloat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedFloat").msgclass
    RepeatedInt64 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedInt64").msgclass
    RepeatedUInt64 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedUInt64").msgclass
    RepeatedInt32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedInt32").msgclass
    RepeatedUInt32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedUInt32").msgclass
    RepeatedBool = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedBool").msgclass
    RepeatedString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedString").msgclass
    RepeatedBytes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedBytes").msgclass
    RepeatedEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedEnum").msgclass
  end
end
