# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/repeated_wrappers.proto

require 'google/protobuf'

require 'protip/extensions_pb'


descriptor_data = "\n\'protip/messages/repeated_wrappers.proto\x12\x0fprotip.messages\x1a\x17protip/extensions.proto\" \n\x0eRepeatedDouble\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x1f\n\rRepeatedFloat\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x1f\n\rRepeatedInt64\x12\x0e\n\x06values\x18\x01 \x03(\x03\" \n\x0eRepeatedUInt64\x12\x0e\n\x06values\x18\x01 \x03(\x04\"\x1f\n\rRepeatedInt32\x12\x0e\n\x06values\x18\x01 \x03(\x05\" \n\x0eRepeatedUInt32\x12\x0e\n\x06values\x18\x01 \x03(\r\"\x1e\n\x0cRepeatedBool\x12\x0e\n\x06values\x18\x01 \x03(\x08\" \n\x0eRepeatedString\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1f\n\rRepeatedBytes\x12\x0e\n\x06values\x18\x01 \x03(\x0c\"\x1e\n\x0cRepeatedEnum\x12\x0e\n\x06values\x18\x01 \x03(\x05P\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    RepeatedDouble = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedDouble").msgclass
    RepeatedFloat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedFloat").msgclass
    RepeatedInt64 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedInt64").msgclass
    RepeatedUInt64 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedUInt64").msgclass
    RepeatedInt32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedInt32").msgclass
    RepeatedUInt32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedUInt32").msgclass
    RepeatedBool = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedBool").msgclass
    RepeatedString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedString").msgclass
    RepeatedBytes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedBytes").msgclass
    RepeatedEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.RepeatedEnum").msgclass
  end
end
