# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/test.proto

require 'google/protobuf'

require 'protip/messages/repeated_wrappers_pb'
require 'protip/messages/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protip.messages.EnumTest" do
    optional :enum, :message, 1, "protip.messages.EnumValue"
    optional :repeated_enums, :message, 2, "protip.messages.RepeatedEnum"
  end
  add_enum "protip.messages.EnumTest.Enum" do
    value :ZERO, 0
    value :ONE, 1
  end
end

module Protip
  module Messages
    EnumTest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumTest").msgclass
    EnumTest::Enum = Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumTest.Enum").enummodule
  end
end

# -- Protip hack until https://github.com/google/protobuf/issues/1198 is resolved
Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumTest").lookup("enum").instance_variable_set(:"@_protip_enum_value", "protip.messages.EnumTest.Enum")
Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumTest").lookup("repeated_enums").instance_variable_set(:"@_protip_enum_value", "protip.messages.EnumTest.Enum")
