# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/test.proto

require 'google/protobuf'

require 'protip/messages/repeated_wrappers_pb'
require 'protip/messages/wrappers_pb'


descriptor_data = "\n\x1aprotip/messages/test.proto\x12\x0fprotip.messages\x1a\'protip/messages/repeated_wrappers.proto\x1a\x1eprotip/messages/wrappers.proto\"\xce\x01\n\x08\x45numTest\x12L\n\x04\x65num\x18\x01 \x01(\x0b\x32\x1a.protip.messages.EnumValueB\"\x8a\xb1\xef\x36\x1dprotip.messages.EnumTest.Enum\x12Y\n\x0erepeated_enums\x18\x02 \x01(\x0b\x32\x1d.protip.messages.RepeatedEnumB\"\x8a\xb1\xef\x36\x1dprotip.messages.EnumTest.Enum\"\x19\n\x04\x45num\x12\x08\n\x04ZERO\x10\x00\x12\x07\n\x03ONE\x10\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    EnumTest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumTest").msgclass
    EnumTest::Enum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumTest.Enum").enummodule
  end
end

# -- Protip hack until https://github.com/google/protobuf/issues/1198 is resolved
Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumTest").lookup("enum").instance_variable_set(:"@_protip_enum_value", "protip.messages.EnumTest.Enum")
Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumTest").lookup("repeated_enums").instance_variable_set(:"@_protip_enum_value", "protip.messages.EnumTest.Enum")
