# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/types.proto

require 'google/protobuf'


descriptor_data = "\n\x1bprotip/messages/types.proto\x12\x0fprotip.messages\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x03\x12\r\n\x05month\x18\x02 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\rb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    Date = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.Date").msgclass
  end
end
