# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/wrappers.proto

require 'google/protobuf'

require 'protip/extensions'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protip.messages.EnumValue" do
    optional :value, :int32, 1
  end
end

module Protip
  module Messages
    EnumValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumValue").msgclass
  end
end
