# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/wrappers.proto

require 'google/protobuf'

require 'protip/extensions_pb'


descriptor_data = "\n\x1eprotip/messages/wrappers.proto\x12\x0fprotip.messages\x1a\x17protip/extensions.proto\"\x1a\n\tEnumValue\x12\r\n\x05value\x18\x01 \x01(\x05P\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    EnumValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.EnumValue").msgclass
  end
end
