# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/active_support/time_with_zone.proto

require 'google/protobuf'


descriptor_data = "\n3protip/messages/active_support/time_with_zone.proto\x12\x1dprotip.messages.ActiveSupport\"=\n\x0cTimeWithZone\x12\x15\n\rutc_timestamp\x18\x01 \x01(\x03\x12\x16\n\x0etime_zone_name\x18\x02 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Protip
  module Messages
    module ActiveSupport
      TimeWithZone = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.ActiveSupport.TimeWithZone").msgclass
    end
  end
end
