# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages/active_support/time_with_zone.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protip.messages.ActiveSupport.TimeWithZone" do
    optional :utc_timestamp, :int64, 1
    optional :time_zone_name, :string, 2
  end
end

module Protip
  module Messages
    module ActiveSupport
      TimeWithZone = Google::Protobuf::DescriptorPool.generated_pool.lookup("protip.messages.ActiveSupport.TimeWithZone").msgclass
    end
  end
end
