# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/extensions.proto

require 'google/protobuf'

require 'google/protobuf/descriptor'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

