# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/extensions.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protip/extensions.proto", :syntax => :proto3) do
  end
end

