# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/extensions.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'


descriptor_data = "\n\x17protip/extensions.proto\x1a google/protobuf/descriptor.proto:5\n\x0bprotip_enum\x12\x1d.google.protobuf.FieldOptions\x18\x91\xf6\xed\x06 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

