# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages.proto

require 'google/protobuf'

require 'protip/messages/array_pb'
require 'protip/messages/big_decimal_value_pb'
require 'protip/messages/currency_pb'
require 'protip/messages/errors_pb'
require 'protip/messages/money_pb'
require 'protip/messages/range_pb'
require 'protip/messages/repeated_wrappers_pb'
require 'protip/messages/types_pb'
require 'protip/messages/wrappers_pb'
require 'protip/messages/active_support/time_with_zone_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

