# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages.proto

require 'google/protobuf'

require 'protip/messages/array_pb'
require 'protip/messages/big_decimal_value_pb'
require 'protip/messages/currency_pb'
require 'protip/messages/errors_pb'
require 'protip/messages/money_pb'
require 'protip/messages/range_pb'
require 'protip/messages/repeated_wrappers_pb'
require 'protip/messages/types_pb'
require 'protip/messages/wrappers_pb'
require 'protip/messages/active_support/time_with_zone_pb'


descriptor_data = "\n\x15protip/messages.proto\x1a\x1bprotip/messages/array.proto\x1a\'protip/messages/big_decimal_value.proto\x1a\x1eprotip/messages/currency.proto\x1a\x1cprotip/messages/errors.proto\x1a\x1bprotip/messages/money.proto\x1a\x1bprotip/messages/range.proto\x1a\'protip/messages/repeated_wrappers.proto\x1a\x1bprotip/messages/types.proto\x1a\x1eprotip/messages/wrappers.proto\x1a\x33protip/messages/active_support/time_with_zone.protoP\x00P\x01P\x02P\x03P\x04P\x05P\x06P\x07P\x08P\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

