# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protip/messages.proto

require 'google/protobuf'

require 'protip/messages/array'
require 'protip/messages/big_decimal_value'
require 'protip/messages/currency'
require 'protip/messages/errors'
require 'protip/messages/money'
require 'protip/messages/range'
require 'protip/messages/repeated_wrappers'
require 'protip/messages/types'
require 'protip/messages/wrappers'
require 'protip/messages/active_support/time_with_zone'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

